using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

// The plugin is a WPF add-in for N.I.N.A., which is Windows-only, and it calls DPAPI directly.
[assembly: SupportedOSPlatform("windows")]

// N.I.N.A. identifies the plugin by this GUID.
[assembly: Guid("fd1225f8-142d-4cab-9262-8f423822d905")]

// AssemblyVersion and AssemblyFileVersion are generated by the GenerateAstraeusVersionInfo target
// in Astraeus.csproj. Declaring them here as well would collide (CS0579).

[assembly: AssemblyTitle("Astraeus")]
[assembly: AssemblyDescription("Astraeus by Cosmic Vaults: remote control, " +
                               "an autopilot for unattended nights, calibration and image upload.")]
[assembly: AssemblyCompany("Cosmic Vaults")]
[assembly: AssemblyProduct("Astraeus")]
[assembly: AssemblyCopyright("Copyright © 2025-2026 Cosmic Vaults")]

// N.I.N.A. plugin manifest metadata, read by the manifest repository's CreateManifest.ps1. The release
// workflow checks every field is filled. Tags are split on commas and not trimmed, so no spaces after
// them. The images live in the public repository so their URLs never change between releases.
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/CosmicVaults/AstraeusPlugin")]
[assembly: AssemblyMetadata("Homepage", "https://cosmicvaults.com")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/CosmicVaults/AstraeusPlugin/blob/main/CHANGELOG.md")]
[assembly: AssemblyMetadata("Tags", "Observatory,Automation,Autopilot,Remote control,Dome,Roof,Calibration,Cloud,Beta")]
[assembly: AssemblyMetadata("FeaturedImageURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/installer/cosmic-vaults-mark-512.png")]
[assembly: AssemblyMetadata("ScreenshotURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/assets/screenshot.png")]
[assembly: AssemblyMetadata("AltScreenshotURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/assets/screenshot-alt.png")]
[assembly: AssemblyMetadata("LongDescription",
    "Astraeus connects N.I.N.A. to the Astraeus dashboard at CosmicVaults.com, so you can watch and run " +
    "your observatory from a browser, and leave it to image through the night on its own.\n\n" +
    "- Dashboard: the camera, mount, dome or roof, focuser, filter wheel, rotator, flat panel, guider, " +
    "safety monitor, weather station and switch hub report their state live, and most can be operated " +
    "from the browser. N.I.N.A.'s log is shown alongside.\n" +
    "- Control Hub: find a target, send it to the mount and take frames, with a preview of each one.\n" +
    "- Autopilot: the server chooses targets from your projects and the plugin runs the night. It waits " +
    "for dusk, opens the roof, slews, centres, focuses, guides and captures, and secures the observatory " +
    "at dawn. Unsafe conditions, a closing roof and mount limits stop or secure it.\n" +
    "- Autofocus on a schedule, on temperature or filter changes, or when the server recommends it.\n" +
    "- Calibration with masters you generate in N.I.N.A., and background upload of frames to your cloud storage.\n" +
    "- Email alerts for problems that need you, and an optional webcam feed on the dashboard.\n\n" +
    "A Cosmic Vaults account is required. You sign in from the plugin's options page through your own " +
    "browser, so the plugin never sees your password. What the plugin sends to the server is listed in " +
    "the Privacy section of the README.\n\n" +
    "This is a beta. Please report problems, with your N.I.N.A. log, at " +
    "https://github.com/CosmicVaults/AstraeusPlugin/issues")]

[assembly: ComVisible(false)]
