using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

// The plugin is a WPF add-in for N.I.N.A., which is Windows-only, and it calls DPAPI directly.
[assembly: SupportedOSPlatform("windows")]

// N.I.N.A. identifies the plugin by this GUID.
[assembly: Guid("fd1225f8-142d-4cab-9262-8f423822d905")]

// AssemblyVersion and AssemblyFileVersion are generated by the GenerateAstraeusVersionInfo target
// in Astraeus.csproj. Declaring them here as well would collide (CS0579).

[assembly: AssemblyTitle("Astraeus")]
[assembly: AssemblyDescription("Astraeus Plugin by Cosmic Vaults: Remote Control, Automated " +
                               "Multi-Night Imaging, Image Cloud Storage, Image Calibration and much more.")]
[assembly: AssemblyCompany("Cosmic Vaults")]
[assembly: AssemblyProduct("Astraeus")]
[assembly: AssemblyCopyright("Copyright © 2025-2026 Cosmic Vaults")]

// N.I.N.A. plugin manifest metadata, read by the manifest repository's CreateManifest.ps1. The release
// workflow checks every field is filled. Tags are split on commas and not trimmed, so no spaces after
// them. The images live in the public repository so their URLs never change between releases.
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/CosmicVaults/AstraeusPlugin")]
[assembly: AssemblyMetadata("Homepage", "https://cosmicvaults.com")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/CosmicVaults/AstraeusPlugin/blob/main/CHANGELOG.md")]
[assembly: AssemblyMetadata("Tags", "Observatory,Automation,Autopilot,Remote control,Dome,Roof,Calibration,Cloud,Beta")]
[assembly: AssemblyMetadata("FeaturedImageURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/installer/cosmic-vaults-mark-512.png")]
[assembly: AssemblyMetadata("ScreenshotURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/assets/screenshot.png")]
[assembly: AssemblyMetadata("AltScreenshotURL", "https://raw.githubusercontent.com/CosmicVaults/AstraeusPlugin/main/assets/screenshot-alt.png")]
[assembly: AssemblyMetadata("LongDescription",
    "Monitor and control your observatory from any device, anywhere. Astraeus puts your whole N.I.N.A. " +
    "rig in the browser on your phone, tablet or computer, live, with nothing else to install. Check in " +
    "from the couch or from the other side of the world, then hand the night to the Autopilot and wake " +
    "up to the night's frames waiting in your cloud storage.\n\n" +
    "- Your whole observatory, live: camera, mount, dome or roof, focuser, filter wheel, rotator, flat " +
    "panel, guider, safety monitor, weather station and switch hub, all updating in real time, and most " +
    "of them yours to drive with a tap or a click. N.I.N.A.'s log streams alongside, so you always know " +
    "what's happening.\n" +
    "- Control Hub: search for any object, preview its field on the sky, send it to the mount and start " +
    "shooting, with a preview of every frame as it lands.\n" +
    "- Autopilot: set up your projects and let Astraeus run the night for you, night after night. The " +
    "server picks what to image next, and the plugin waits for dusk, opens the roof, slews, centres, " +
    "focuses, guides and captures, then secures everything at dawn. Bad weather, a closing roof or a mount " +
    "limit, and it stops or makes the observatory safe on its own.\n" +
    "- Sharp all night: autofocus on a schedule, on temperature or filter changes, or let Smart Autofocus " +
    "decide when it's needed.\n" +
    "- Calibrated and backed up: frames are calibrated on your PC with masters you generate in N.I.N.A., " +
    "and uploaded to your cloud storage in the background.\n" +
    "- Stay in the loop: an email when something needs you (a critical error, the roof opening or " +
    "closing, cloud storage filling up), a note when an Autopilot session starts and ends or a project " +
    "completes, and an optional Nightly Image Summary of everything captured while you slept.\n" +
    "- See it for yourself: an optional all-sky or observatory webcam, live on the dashboard.\n\n" +
    "A Cosmic Vaults account is required. You sign in from the plugin's options page through your own " +
    "browser.\n\n" +
    "This is a beta. Please report problems, with your N.I.N.A. log, at " +
    "https://github.com/CosmicVaults/AstraeusPlugin/issues")]

[assembly: ComVisible(false)]
